import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/tokens.css";
import "@/styles/base.css";

const jost = localFont({
  src: "./fonts/jost.woff2",
  weight: "100 900",
  display: "swap",
  variable: "--font-sans",
});

const playfair = localFont({
  src: [
    { path: "./fonts/playfair.woff2", weight: "400 900", style: "normal" },
    { path: "./fonts/playfair-italic.woff2", weight: "400 900", style: "italic" },
  ],
  display: "swap",
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={`${jost.variable} ${playfair.variable}`}>
      <body>{children}</body>
    </html>
  );
}
